name: Lua CI

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check ./lua

  lint:
    runs-on: ubuntu-latest
    env:
      GLUAFIXER_VERSION: 1.26.0

    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Get any changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **.lua

      # TODO: Kill this
      - name: Run E2 Extension Preprocessor
        run: |
          lua .github/workflows/preprocess.lua ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Download GLuaFixer
        run: |
          curl --retry 3 --location https://github.com/FPtje/GLuaFixer/releases/download/$GLUAFIXER_VERSION/glualint-$GLUAFIXER_VERSION-x86_64-linux.zip --output gluafixer.zip
          unzip gluafixer.zip

      - name: Lint Code
        run: |
          ./glualint --output-format github --config .glualint.json lint ./lua
