name: Push to release branch

on:
  push:
    branches: master

jobs:
  lua:
    uses: "./.github/workflows/lua.yml"

  deploy:
    runs-on: ubuntu-latest
    # TODO: Re-enable this once the whole codebase passes the formatter and linter
    #needs: [lua]

    environment: production
    concurrency: production

    steps:
      # TODO: Upgrade this to v2 deployment when bundling added
      - name: Post to webhook
        run: curl --fail-with-body -X POST ${{ secrets.DEPLOYER_WEBHOOK }}/${{ github.event.repository.name }}
